[package]
name = "nimbus_vault_server_domain"
version = "0.1.0"
edition = "2024"

[dependencies]
nimbus_vault_server_shared = { path = "../shared" }

# Common
ulid = { version = "1.2.1" }
chrono = { version = "0.4.41"}